Perform\UserBundle\Entity\User:
    type: entity
    table: perform_user_user
    repositoryClass: Perform\UserBundle\Repository\UserRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        forename:
            type: string
        surname:
            type: string
        password:
            type: string
        passwordExpiresAt:
            type: datetime
        email:
            type: string
            unique: true
        roles:
            type: array
        lastLogin:
            type: datetime
            nullable: true
    oneToMany:
        resetTokens:
            targetEntity: ResetToken
            mappedBy: user
            cascade:
                - remove
