perform_user_password_forgot:
    path: /
    defaults:
        _controller: PerformUserBundle:Password:forgotPassword

perform_user_password_reset:
    path: /{id}/{secret}
    defaults:
        _controller: PerformUserBundle:Password:resetPassword

perform_user_password_success:
    path: /success
    defaults:
        _controller: PerformUserBundle:Password:success
