perform_user_password_forgot:
    path: /reset-password
    defaults:
        _controller: PerformUserBundle:Password:forgotPassword

perform_user_password_reset:
    path: /reset-password/{id}/{secret}
    defaults:
        _controller: PerformUserBundle:Password:resetPassword

perform_user_password_success:
    path: /reset-password/success
    defaults:
        _controller: PerformUserBundle:Password:success
