imports:
    - services/console.yml

services:
    perform_user.listener.login:
        class: Perform\UserBundle\EventListener\LoginListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: security.interactive_login, method: onLogin}

    perform_user.listener.new_password:
        class: Perform\UserBundle\EventListener\NewPasswordListener
        arguments:
            - '@security.token_storage'
            - '@perform_user.user_manager'
            - '@form.factory'
            - '@twig'
        tags:
            - {name: kernel.event_listener, event: kernel.request}

    perform_user.crud.user:
        class: Perform\UserBundle\Crud\UserCrud
        tags:
            - {name: perform_base.crud, crud_name: "perform_user.user"}

    perform_user.menu_link.users:
        class: Perform\BaseBundle\EventListener\SimpleMenuListener
        arguments:
            - 'users'
            - 'perform_user.user'
            - null
            - 'users'
        tags:
            - { name: kernel.event_listener, event: perform_base.menu.build, method: onMenuBuild }

    perform_user.doctrine.user_listener:
        class: Perform\UserBundle\Doctrine\UserListener
        tags:
            - { name: doctrine.event_subscriber }

    perform_user.importer.user:
        class: Perform\UserBundle\Importer\UserImporter
        arguments: ["@doctrine.orm.entity_manager"]

    perform_user.repo.user:
        class: Perform\UserBundle\Repository\UserRepository
        arguments: ['PerformUserBundle:User']
        factory: ['@doctrine.orm.entity_manager', 'getRepository']

    perform_user.user_manager:
        class: Perform\UserBundle\Security\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            # in seconds, roughly 5 years
            - 157680000

    perform_user.reset_token_manager:
        class: Perform\UserBundle\Security\ResetTokenManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@perform_user.user_manager"
            - "@perform_base.doctrine.entity_resolver"
            - "@perform_notification.notifier"

    perform_user.action.create_reset_token:
        class: Perform\UserBundle\Action\CreateResetTokenAction
        arguments:
            - "@perform_user.reset_token_manager"
        tags:
            - { name: perform_base.action, alias: perform_user_create_reset_token }

    Perform\UserBundle\Controller\:
        resource: '../../Controller'
        autoconfigure: true
        tags:
            - controller.service_arguments

    Perform\UserBundle\Controller\UserController:
        parent: Perform\BaseBundle\Controller\CrudController

    perform_user.auth.single_use:
        class: Perform\UserBundle\Security\SingleUseAuthenticator
        arguments:
            - '@uri_signer'

    Perform\UserBundle\Installer\UsersInstaller:
        arguments:
            - '@perform_user.importer.user'
            - '%kernel.root_dir%/config/perform_users.yml'
        tags:
            - perform_base.installer
