services:
    Perform\UserBundle\Command\CreateUserCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@perform_base.doctrine.entity_resolver'
        tags:
            - console.command

    Perform\UserBundle\Command\ResetPasswordCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@perform_base.doctrine.entity_resolver'
        tags:
            - console.command

    Perform\UserBundle\Command\UpdateRolesCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@perform_base.doctrine.entity_resolver'
        tags:
            - console.command

    Perform\UserBundle\Command\PurgeResetTokensCommand:
        arguments:
            - '@perform_user.reset_token_manager'
        tags:
            - console.command
