perform_user_forgot_password:
    path: /
    defaults:
        _controller: Perform\UserBundle\Controller\ForgotPasswordController::forgot

perform_user_forgot_password_reset:
    path: /reset
    defaults:
        _controller: Perform\UserBundle\Controller\ForgotPasswordController::reset

perform_user_forgot_password_success:
    path: /success
    defaults:
        _controller: Perform\UserBundle\Controller\ForgotPasswordController::success
